// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  var Str, Strings, Words, changeCase, delimiter, _,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Strings = Str = _ = require('strings.js');

  changeCase = function(method, args) {
    var index, pos, _i, _j, _k, _len, _len1, _ref, _results, _results1, _results2;
    if (_.isString(args != null ? args[0] : void 0)) {
      return this.set(Str[method].apply(Str, [this.$].concat(__slice.call(args))));
    } else if ((args != null ? args[0] : void 0) === 0) {
      _results = [];
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        pos = args[_i];
        _results.push((function() {
          var _j, _ref, _results1;
          _results1 = [];
          for (index = _j = 0, _ref = this.count - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; index = 0 <= _ref ? ++_j : --_j) {
            _results1.push(this.words[index] = Str[method](this.words[index], pos));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    } else {
      if (args.length < 1) {
        args = (function() {
          _results1 = [];
          for (var _j = 0, _ref = this.count; 0 <= _ref ? _j <= _ref : _j >= _ref; 0 <= _ref ? _j++ : _j--){ _results1.push(_j); }
          return _results1;
        }).apply(this);
      }
      _results2 = [];
      for (_k = 0, _len1 = args.length; _k < _len1; _k++) {
        pos = args[_k];
        pos = _.positiveIndex(pos, this.count);
        _results2.push(this.words[pos] = Str[method](this.words[pos]));
      }
      return _results2;
    }
  };

  delimiter = ' ';

  Words = (function(_super) {
    __extends(Words, _super);

    function Words() {
      Object.defineProperty(this, '$', {
        get: function() {
          return this.get();
        }
      });
      Object.defineProperty(this, 'string', {
        get: function() {
          return this.get();
        }
      });
      Object.defineProperty(this, 'count', {
        get: function() {
          return this.words.length;
        }
      });
      this.set.apply(this, arguments);
    }

    Words.prototype.set = function() {
      var arg, str, _i, _j, _len, _len1, _ref;
      if (arguments.length < 1) {
        return this;
      }
      this.words = [];
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        arg = arguments[_i];
        _ref = Str.split(Str.create(arg), delimiter);
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          str = _ref[_j];
          this.words.push(str);
        }
      }
      return this;
    };

    Words.prototype.get = function() {
      var index, string, _i, _len;
      if (arguments.length < 1) {
        return this.words.join(delimiter);
      }
      string = '';
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        index = arguments[_i];
        index = _.positiveIndex(index, this.count);
        if (index !== false) {
          string += this.words[index] + delimiter;
        }
      }
      return Str.trim(string);
    };

    Words.prototype.xs = function(callback) {
      var index, response, result, word, _i, _len, _ref;
      if (callback == null) {
        callback = function() {
          return true;
        };
      }
      if (_.notFunction(callback) || this.count < 1) {
        return;
      }
      result = [];
      _ref = this.words;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        word = _ref[index];
        if (response = callback(word, index)) {
          if (response === true) {
            result.push(word);
          } else if (_.isStringOrNumber(response)) {
            result.push(response);
          }
        }
      }
      this.words = result;
      return this;
    };

    Words.prototype.find = function(string, showPositions) {
      var indices;
      indices = [];
      if ('' !== (string = Str.force(string))) {
        this.xs(function(word, index) {
          var position, _i, _len, _ref, _results;
          _ref = Str.find(word, string);
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            position = _ref[_i];
            if (showPositions) {
              _results.push(indices.push([index + 1, position]));
            } else {
              _results.push(indices.push(index + 1));
            }
          }
          return _results;
        });
      }
      return indices;
    };

    Words.prototype.applyToValidIndex = function(orgIndex, callback) {
      var index;
      if (false !== (index = _.positiveIndex(orgIndex, this.count))) {
        callback(index);
      }
      return this;
    };

    Words.prototype.upper = function() {
      changeCase.call(this, 'upper', Array.prototype.slice.call(arguments));
      return this;
    };

    Words.prototype.lower = function() {
      changeCase.call(this, 'lower', Array.prototype.slice.call(arguments));
      return this;
    };

    Words.prototype.reverse = function() {
      var arg, _i, _len;
      if ((arguments != null ? arguments[0] : void 0) === 0) {
        this.xs(function(word) {
          return Str.reverse(word);
        });
      } else if (arguments.length > 0) {
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          arg = arguments[_i];
          this.applyToValidIndex(arg, (function(_this) {
            return function(index) {
              return _this.words[index] = Str.reverse(_this.words[index]);
            };
          })(this));
        }
      } else {
        this.set(Str.reverse(this.$));
      }
      return this;
    };

    Words.prototype.shuffle = function(selection) {
      var arg, _i, _j, _len, _len1;
      if (selection != null) {
        if (_.isString(selection)) {
          for (_i = 0, _len = arguments.length; _i < _len; _i++) {
            arg = arguments[_i];
            this.xs((function(_this) {
              return function(word, index) {
                if (word === arg) {
                  return Str.shuffle(word);
                }
                return true;
              };
            })(this));
          }
        } else if (selection === 0) {
          this.xs(function(word) {
            return Str.shuffle(word);
          });
        } else {
          for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
            arg = arguments[_j];
            this.applyToValidIndex(arg, (function(_this) {
              return function(index) {
                return _this.words[index] = Str.shuffle(_this.words[index]);
              };
            })(this));
          }
        }
      } else {
        this.words = _.shuffleArray(this.words);
      }
      return this;
    };

    Words.prototype.clear = function() {
      this.words = [];
      return this;
    };

    Words.prototype.remove = function() {
      var arg, _i, _len;
      if (arguments.length < 1) {
        return this;
      }
      if ((arguments != null ? arguments[0] : void 0) === 0) {
        return this.clear();
      }
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        arg = arguments[_i];
        if (_.isString(arg)) {
          this.xs(function(word) {
            if (word !== arg) {
              return true;
            }
          });
        } else {
          this.xs((function(_this) {
            return function(word) {
              if (word !== _this.words[_.positiveIndex(arg, _this.count)]) {
                return true;
              }
            };
          })(this));
        }
      }
      return this;
    };

    Words.prototype.pop = function(amount) {
      var n, _i;
      if (amount == null) {
        amount = 1;
      }
      for (n = _i = 1; 1 <= amount ? _i <= amount : _i >= amount; n = 1 <= amount ? ++_i : --_i) {
        this.words.pop();
      }
      return this;
    };

    Words.prototype.push = function() {
      var arg, _i, _len;
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        arg = arguments[_i];
        if (_.isStringOrNumber(arg)) {
          this.words.push(Str.trim(arg));
        }
      }
      return this;
    };

    Words.prototype.shift = function(amount) {
      var n, _i;
      if (amount == null) {
        amount = 1;
      }
      for (n = _i = 1; 1 <= amount ? _i <= amount : _i >= amount; n = 1 <= amount ? ++_i : --_i) {
        this.words.shift();
      }
      return this;
    };

    Words.prototype.prepend = function() {
      var arg, _i, _len;
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        arg = arguments[_i];
        if (_.isStringOrNumber(arg)) {
          this.words.unshift(Str.trim(arg));
        }
      }
      return this;
    };

    Words.prototype.insert = function() {
      var index, word, words, _i, _len;
      index = arguments[0], words = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (_.isString(index)) {
        return this.prepend.apply(this, arguments);
      }
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        this.words.splice(index, 0, Str.trim(word));
      }
      return this;
    };

    Words.prototype.replace = function(selection, replacement) {
      if (replacement == null) {
        replacement = '';
      }
      if ('' === (replacement = Str.trim(replacement))) {
        return this;
      }
      if (_.isNumber(selection)) {
        this.applyToValidIndex(selection, (function(_this) {
          return function(index) {
            return _this.words.splice(index, 1, replacement);
          };
        })(this));
      } else {
        this.xs(function(word) {
          if (word === selection) {
            return replacement;
          }
          return true;
        });
      }
      return this;
    };

    return Words;

  })(Strings);

  Words.prototype.unshift = Words.prototype.prepend;

  if (typeof window !== "undefined" && window !== null) {
    return window.Words;
  }

  if (module) {
    return module.exports = Words;
  }

}).call(this);
